- name: Validating that Helm is already installed
  command: which helm
  ignore_errors: true
  register: HELM_EXISTS_STATUS

- name: Validating that Kubectl is already installed
  command: which kubectl
  ignore_errors: true
  register: KUBECTL_EXISTS_STATUS

- name: Validating that Talosctl is already installed
  command: which talosctl
  ignore_errors: true
  register: TALOS_EXISTS_STATUS

- block:
    - name: Installing the Helm dependencies
      apt:
        pkg: apt-transport-https

    - name: Downloading Helm
      unarchive:
        src: "https://get.helm.sh/helm-{{ HELM_VERSION }}-linux-amd64.tar.gz"
        dest: /tmp
        remote_src: true
        mode: 0755

    - name: Installing Helm
      copy:
        src: "/tmp/linux-amd64/helm"
        dest: "/usr/local/bin/helm"
        mode: 0755
        remote_src: true

    - name: Installing Kubernetes Python package
      pip:
        name: kubernetes
  when: 
    - ACTION == "bootstrap_cluster"
    - CILIUM_ENABLE or MAYASTOR_ENABLE
    - HELM_EXISTS_STATUS.rc != 0 or FORCE_REINSTALL_HELM

- block:
    - name: Installing the Kubectl dependencies
      apt:
        pkg:
          - ca-certificates
          - curl

    - name: Adding the Google Cloud signing key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: Adding the Kubernetes package repository
      become: true
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        update_cache: true

    - name: Installing Kubectl
      apt:
        pkg: kubectl
  when: 
    - ACTION == "bootstrap_cluster"
    - KUBECTL_EXISTS_STATUS.rc != 0 or FORCE_REINSTALL_KUBECTL

- block:
    - name: Downloading Talosctl
      get_url:
        url: https://talos.dev/install
        dest: /tmp/install_talosctl.sh
      when: TALOS_EXISTS_STATUS != 0

    - name: Installing Talosctl
      command: sh /tmp/install_talosctl.sh
      when: TALOS_EXISTS_STATUS != 0

    - name: Deleting the temporary files
      file:
        path: /tmp/install_talosctl.sh
        state: absent
  when: 
    - ACTION == "bootstrap_cluster"
    - TALOS_EXISTS_STATUS.rc != 0 or FORCE_REINSTALL_TALOSCTL

- name: Uninstalling Helm
  apt:
    pkg: helm
    state: absent
  when: 
    - ACTION == "destroy_cluster"
    - not PRESERVE_HELM_BINARY

- name: Uninstalling Kubectl
  apt:
    pkg: kubectl
    state: absent
  when: 
    - ACTION == "destroy_cluster"
    - not PRESERVE_KUBECTL_BINARY

- name: Uninstalling Talosctl
  file:
    path: /usr/local/bin/talosctl
    state: absent
  when: 
    - ACTION == "destroy_cluster"
    - not PRESERVE_TALOSCTL_BINARY
